POST http://localhost:3080/abilities/chroma/start
Authorization: Bearer {{PAIOS_BEARER_TOKEN}}
Content-Type: application/json

###

POST http://localhost:3080/abilities/chroma/stop
Authorization: Bearer {{PAIOS_BEARER_TOKEN}}
Content-Type: application/json
