# API testing with Visual Studio Code - REST Client Extention

POST http://localhost:3080/api/v1/assets
Authorization: Bearer {{PAIOS_BEARER_TOKEN}}
Content-Type: application/json

{
  "title": "Attention Is All You Need",
  "creator": "Ashish Vaswani et al",
  "subject": "Artificial Intelligence",
  "description": "We propose a new simple network architecture, the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely."
}

###

PUT http://localhost:3080/api/v1/assets/1cbb0bc5-bae2-4b9d-9555-f2282f767047
Authorization: Bearer {{PAIOS_BEARER_TOKEN}}
Content-Type: application/json

{
  "title": "Generative Adversarial Networks",
  "creator": "Goodfellow et al",
  "subject": "Artificial Intelligence",
  "description": "We propose a new framework for estimating generative models via an adversarial process, in which we simultaneously train two models: a generative model G that captures the data distribution, and a discriminative model D that estimates the probability that a sample came from the training data rather than G."
}

###

GET http://localhost:3080/api/v1/assets/1cbb0bc5-bae2-4b9d-9555-f2282f767047
Authorization: Bearer {{PAIOS_BEARER_TOKEN}}
Content-Type: application/json

###

DELETE http://localhost:3080/api/v1/assets/1cbb0bc5-bae2-4b9d-9555-f2282f767047
Authorization: Bearer {{PAIOS_BEARER_TOKEN}}
Content-Type: application/json
