# API testing with Visual Studio Code - REST Client Extention

POST http://localhost:3080/api/v1/channels
Authorization: Bearer {{PAIOS_BEARER_TOKEN}}
Content-Type: application/json

{
    "name": "My Channel",
    "uri": "http://localhost:3080/channels/my-channel"
}

###
PUT http://localhost:3080/api/v1/channels/llm-api
Authorization: Bearer {{PAIOS_BEARER_TOKEN}}
Content-Type: application/json

{
    "id": "llm-api",
    "name": "LLM API",
    "uri": "http://localhost:3080/channels/llm-api"
}

###
PUT http://localhost:3080/api/v1/channels/imap-sync
Authorization: Bearer {{PAIOS_BEARER_TOKEN}}
Content-Type: application/json

{
    "id": "imap-sync",
    "name": "E-mail Sync (IMAP)",
    "uri": "imap://imap.gmail.com:993"
}

###

DELETE http://localhost:3080/api/v1/channels/llm-api
Authorization: Bearer {{PAIOS_BEARER_TOKEN}}
Content-Type: application/json

###

GET http://localhost:3080/api/v1/channels/llm-api
Authorization: Bearer {{PAIOS_BEARER_TOKEN}}
Content-Type: application/json

###

GET http://localhost:3080/api/v1/channels
Authorization: Bearer {{PAIOS_BEARER_TOKEN}}
Content-Type: application/json
