### Test single large download

POST http://localhost:3080/api/v1/downloads
Content-Type: application/json

[
    {
        "source_url": "https://releases.ubuntu.com/24.04/ubuntu-24.04-desktop-amd64.iso",
        "file_name": "ubuntu-24.04-desktop-amd64.iso"
    }
]

### Test single small download

POST http://localhost:3080/api/v1/downloads
Content-Type: application/json

[
    {
        "source_url": "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.5.0-amd64-netinst.iso",
        "file_name": "debian-12.5.0-amd64-netinst.iso"
    }
]

### Test download without filename specified

POST http://localhost:3080/api/v1/downloads
Content-Type: application/json

[
    {
        "source_url": "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.5.0-amd64-netinst.iso"
    }
]

### Test multiple downloads

POST http://localhost:3080/api/v1/downloads
Content-Type: application/json

[
    { "source_url": "https://releases.ubuntu.com/24.04/ubuntu-24.04-desktop-amd64.iso", "file_name": "ubuntu-24.04-desktop-amd64.iso" },
    { "source_url": "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.5.0-amd64-netinst.iso", "file_name": "debian-12.5.0-amd64-netinst.iso" }
]

###

POST http://localhost:3080/api/v1/downloads
Content-Type: application/json

[
    {
        "source_url": "https://releases.ubuntu.com/24.04/ubuntu-24.04-desktop-amd64.iso",
        "file_name": "ubuntu-24.04-desktop-amd64.iso",
    }
]

###

POST http://localhost:3080/api/v1/downloads
Content-Type: application/json

[
    {
        "source_url": "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.5.0-amd64-netinst.iso",
        "file_name": "ubuntu-24.04-desktop-amd64.iso",
        "hash_type": "sha512",
        "expected_hash": "33c08e56c83d13007e4a5511b9bf2c4926c4aa12fd5dd56d493c0653aecbab380988c5bf1671dbaea75c582827797d98c4a611f7fb2b131fbde2c677d5258ec9"
    }
]

###

POST http://localhost:3080/api/v1/downloads/ac56536c-96a1-4dda-a664-d2262cbf5c7e/pause
Content-Type: application/json

###

POST http://localhost:3080/api/v1/downloads/ac56536c-96a1-4dda-a664-d2262cbf5c7e/resume
Content-Type: application/json

###

GET http://localhost:3080/api/v1/downloads/4fd98231-02ab-4321-ac57-d9dc96fa6d01
Content-Type: application/json

###

DELETE http://localhost:3080/api/v1/downloads/83bdac3a-e5de-4783-a9b9-dabdcae2a1d2
Content-Type: application/json
